---
apiVersion: batch/v1
kind: Job
metadata:
  name: test
  namespace: k8s-openstack
spec:
  template:
    spec:
      containers:
      - name: test
        image: sumikof/k8s-openstack-client
        command: ["sleep",  "3000"]
        envFrom:
        - configMapRef:
            name: admin-config
        env:
        - name: OS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: admin-secret
              key: OS_PASSWORD
      restartPolicy: Never
  backoffLimit: 4
